DATASET = "D_W_15K_V1"

if DATASET == "D_W_15K_V1":
    KG1_PATH_FOR_NAMES = 'DBpedia_names.xlsx'
    KG2_PATH_FOR_NAMES = 'Wikidata_names.xlsx'
elif DATASET == "BBC_DB":
    KG1_PATH_FOR_NAMES = 'BBC_names.xlsx'
    KG2_PATH_FOR_NAMES = 'DBpedia_names.xlsx'
elif DATASET == "D_W_15K_V2":
    KG1_PATH_FOR_NAMES = 'DBpedia_names.xlsx'
    KG2_PATH_FOR_NAMES = 'Wikidata_names.xlsx'
elif DATASET == "SRPRS_D_W_15K_V1":
    KG1_PATH_FOR_NAMES = 'DBpedia_names.xlsx'
    KG2_PATH_FOR_NAMES = 'Wikidata_names.xlsx'
elif DATASET == "SRPRS_D_W_15K_V2":
    KG1_PATH_FOR_NAMES = 'DBpedia_names.xlsx'
    KG2_PATH_FOR_NAMES = 'Wikidata_names.xlsx'


TASK = "entity-alignment"

RANDOM_INITIALIZATION = False
if RANDOM_INITIALIZATION:
    HIDDEN_SIZE = 256
else:
    HIDDEN_SIZE = 768
    
NUM_HIDDEN_LAYERS = 12
NUM_ATTENTION_HEADS = 4
INPUT_DROPOUT_PROB = 0.5
ATTENTION_DROPOUT_PROB = 0.1
HIDDEN_DROPOUT_PROB = 0.3
RESIDUAL_DROPOUT_PROB = 0.1
INITIALIZER_RANGE = 0.02
INTERMEDIATE_SIZE = 2048
RESIDUAL_W = 0.5
EPOCH = 200
MIN_EPOCHS = 10
LEARNING_RATE = 5e-4
BATCH_SIZE = 2048
EVAL_BATCH_SIZE = 4096
EARLY_STOP_MAX_TIMES = 3
SOFT_LABEL = 0.25
EVAL_FREQ = 5
START_EVAL = 0
SWA_PRE_NUM = 5
DO_TRAIN = True
DO_TEST = True
USE_GELU = False
ADDITION_LOSS_W = 0.1
RELATION_COMBINE_DROPOUT_PROB = 0.2
CSLS = 2

if DATASET == "D_W_15K_V1":
    VOC_LIM_1 = 15100
    VOC_LIM_2 = 27100
elif DATASET == "BBC_DB":
    VOC_LIM_1 = 9496
    VOC_LIM_2 = 17013
elif DATASET == "D_W_15K_V2":
    VOC_LIM_1 = 15100
    VOC_LIM_2 = 27100
elif DATASET == "SRPRS_D_W_15K_V1":
    VOC_LIM_1 = 15100
    VOC_LIM_2 = 27100
elif DATASET == "SRPRS_D_W_15K_V2":
    VOC_LIM_1 = 15100
    VOC_LIM_2 = 27100