import pickle

# def truncated_normal(size=768, threshold=0.02):
    # values = truncnorm.rvs(-threshold, threshold, size=size)
    # return values

# dictionary with key: entity id and value: entity name embedding (generated by sentenceBERT)
# if entity has not name, then value: random embedding (generated by truncated_normal)
with open("names_emb.pickle", "rb") as file:
    embs = pickle.load(file)

# list of entity ids that have not name
# for D_W_15K_V1 only some entities of Wikidata have not names
with open("unknown_ents_list.pickle", "rb") as file:
    unknown_ents = pickle.load(file)
    
# create numpy array from dictionary
# each row corresponds to an entity id
# e.g., entity with id = 0 has name embedding name_embs[0]
#       entity with id = 1 has name embedding name_embs[1] etc
name_embs = []
for id in embs:
    name_embs.append(embs[id])
name_embs = np.array(name_embs)

print(name_embs)

# (30000, 768)
print(name_embs.shape)

print(unknown_ents)

# 3707
print(len(unknown_ents))